name: Automated Tests
on: pull_request
jobs:
  buzzy-finance-integration-tests:
    name: Build, Test, and Lint with Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
      - run: pnpm lint:check
